### ISSUE TITLE
Create end of year summary

### ISSUE THREAD

**Issue by wdoug** [codefordenver/org#28]
As a potential funder of CfD, I would like to know the expected impact of my donations.

## Examples: 
- https://www.kickstarter.com/year/2014/data
- http://2014.thoughtbot.com/
- http://www.kiva.org/annualreport
- https://www.codeschool.com/2014

## Things to investigate adding to summary
- Volunteer hours (sparktime)
- Partners worked with
- Lines of code written / updated (github)
- documents uploaded / created in google drive
- Cost (i.e. dollars spent)
- flowdock conversations?
- food eaten?
- quotes from partners?
- CodeAcross video?
- survey results
- people signed up on meetup / flowdock

---

## Spikes 

- [ ] spike on github query for # of contributors (tom)
- [ ] spike on google docs query for # of docs (hayden)
- [ ]  spike on meetup api esp. # of meetings / events (david)
- [ ] spike on sparktime API talk to Willy
- [ ] spike on flowdock API, talk to Willy

**Comment by dviramontes** [comment]
- [] make github query for # of contributor

**Comment by dviramontes** [comment]
for sparktime data look at: http://sparktime.org/activity

**Comment by dviramontes** [comment]
one public meetup endpoint we can use to visualize data: https://api.meetup.com/2/groups?offset=0&format=json&group_urlname=CodeForDenver&photo-host=public&page=20&radius=25.0&fields=&order=id&desc=false&sig_id=13984801&sig=232c2fc2c46fca4d53fa5cce43d90bc1e669a7d1

**Comment by haydenevans** [comment]
For Google Docs, here's what I found: https://developers.google.com/drive/v2/web/file
It looks like we should be able to accomplish what we want to (number of Google Docs) with the "File Reference" metadata via the Drive API

**Comment by jenshurley** [comment]
I talked to Ling (who works in funding) about how tech requests are evaluated. In general, 
###funders like to see 
- stable leadership 
- tracking of outcomes over time (data- and impact-driven)
- since we're volunteer based (which is generally not thought to be stable), how do we add stability through member engagement (skill and community building) and our model?

So I would like to suggest we also show some quant and qual data about what the core team has done this year to 
##indicate core team stability 
 - break out the commits, hours, documents of core team to display
 - Bios that show that the core team's commitment - how long people have been doing community/hacking work can support the case that we're in it for the long haul. (maybe more for website than summary) 
 - I can take on some of the qual piece because I'm doing it anyway for the content strategy work.

#show member engagement
-some highlighted tweets
-photos of groups at work
-stuff we do on 

###our model
it's a work-in-progress, but the process adaptations such as 
 - roles
 - stand-ups
 - pomodoros
seem noteworthy. 

So my hypothesis is that funders want to see us tell a story about stability, engagement, and our operating model.

**Comment by karenderrickdavis** [comment]
In our model, where Rally/CA has demonstrated a commitment (through allowing Willy time to commit to the Brigade) and provided funding, that is a demonstration of stability, as well. I don't know if traditional foundation funders think to consider the impact of Corporate Social Responsibility's affect on the stability of a project.  Great work, Jen!
